initial commit, slowly work from interface into the kernel
TimDettmers/bitsandbytes pull request #188
Opened 2023-03-09 16:09 UTC by lucidrains

work in progress

2023-03-09 20:35 UTC, lucidrains commented
autoregressive enwik8 with lion8bit converged successfully, even though there's some inaccuracies in kernel.cu

2023-03-09 21:20 UTC, lucidrains commented
<img width="439" alt="Screen Shot 2023-03-09 at 1 20 12 PM" src="https://user-images.githubusercontent.com/108653/224162419-14567580-ac4d-4bd0-892f-dc383db14e01.png">

2023-03-09 22:37 UTC, lucidrains commented
<img width="359" alt="Screen Shot 2023-03-09 at 2 36 48 PM" src="https://user-images.githubusercontent.com/108653/224176088-996bd08f-4045-4dc1-88b9-ea412e72ec37.png">

weight decay looks good

2023-03-10 06:20 UTC, christallire commented
resolves https://github.com/TimDettmers/bitsandbytes/issues/150

2023-03-10 15:54 UTC, lucidrains commented
@christallire welcome you to build from source and import the `Lion8bit` and give it a try

seems to be working great, thanks to Tim's surrounding scaffold

2023-03-10 18:19 UTC, lucidrains commented
ok, will let this PR sit for a while to gather feedback. probably will revisit it at end of this month and see if we can get it merged

2023-03-18 17:20 UTC, lucidrains commented
i think there may still be an issue with the blockwise version, where the momentum update with beta2 is occuring before the actual parameter updates

2023-03-21 21:45 UTC, TimDettmers requested changes
Thank you for your work on this! This looks almost good to me. The only thing that is off is the order of the updates that you point out. We can get around this without rewriting the CUDA code by using the gradient variable as temporary variable to store the current momentum value + the update value for Lion (see other comments). Please add a comment to these lines to help people understand the use of the gradient as a temporary variable (adding more comments is appreciated, sorry for the mess with the undocumented code). 

The enwiki test runs are great! I think this shows that it works. It would be great to add a test in test_optim.py for Lion. You need three things for that: (1) define lion str2optimizer dictionary entry, (2) define str2statenames dictionary entry, (3) add the optimizer name to  the optimizer_names list for the [test_optimzier8bit](https://github.com/TimDettmers/bitsandbytes/blob/main/tests/test_optim.py#L258) function. That should be all that is needed. The only question is which 32-bit baseline to use. You might want to use your own Lion 32-bit repo. I think a fair test could also be to compare against the 32-bit bnb optimizer (since you have shown that 8-bit already replicates enwiki performance). This might be simpler and quick to write up.

2023-03-21 21:45 UTC, TimDettmers commented on csrc/kernels.cu
> +										s1_vals[j] = s1_vals[j]*beta2 + ((1.0f-beta2)*g_val);
We can add the following line to have the correct order for Lion:

```c
g_vals[j] = lr*sgn(((float)s1_vals[j])*beta1 + ((1.0f-beta1)*((float)g_vals[j])));
 s1_vals[j] = s1_vals[j]*beta2 + ((1.0f-beta2)*g_val);
```
And then we update line 1752 instead with:
```c
p_vals[j] = (float)p_vals[j] - (float)g_vals[j];
```

2023-03-22 01:30 UTC, lucidrains commented
@TimDettmers thank you Tim for the feedback! :pray: will address everything you brought up and poke you when it is ready later this week

2023-04-11 14:22 UTC, TimDettmers commented
Thank you, this looks good to me. The issue with the test is expected. The error from Lion is expected to be higher at times due to its noisy update. I will merge and will have a look at the test. This is an excellent PR, thank you for all the work. I think it will be invaluable to the community!

2023-04-11 14:22 UTC, merged

2024-05-01 19:05 UTC, lucidrains commented
@TimDettmers oh hey Tim! glad to see this merged

thank you for reviewing it and getting it out there!