add sort to get_compute_capabilities
TimDettmers/bitsandbytes pull request #527
Opened 2023-06-20 06:54 UTC by Ronnoc

2023-06-20 06:59 UTC, Ronnoc commented
@TimDettmers Please help review this Pull Request. Thank you.

2023-06-24 06:46 UTC, Dessix commented on bitsandbytes/cuda_setup/main.py
> +    ccs_int_tuple = []
```suggestion
```

2023-06-24 06:51 UTC, Dessix requested changes
Try sorting using sort-by functionality.

2023-06-24 06:51 UTC, Dessix commented on bitsandbytes/cuda_setup/main.py
> +    ccs_int_tuple = []
```suggestion
```

2023-06-24 06:51 UTC, Dessix commented on bitsandbytes/cuda_setup/main.py
> +        ccs.append(f"{major}.{minor}")
```suggestion
        ccs.append(f"{cc_major.value}.{cc_minor.value}")
    ccs.sort(key=lambda v: tuple(map(int, str(v).split("."))))
```

2023-07-09 14:05 UTC, Dessix approved these changes

2024-01-01 16:52 UTC, TimDettmers commented
Thank you for catching this! I think a question is if we should select the highest or lowest compute capability. The lowest would give the most broad support for multiple GPU. However, it is common that one uses an old GPU for monitors and a new GPU for deep learning work. As such, one would want to select the highest compute capability. @Titus-von-Koeller @younesbelkada any thoughts?

2024-01-01 16:54 UTC, TimDettmers commented
I will merge #703 instead as it is more comprehensive, but lets chat a bit about which how we should sort the compute capability

2024-01-18 00:52 UTC, Ronnoc commented
closed this PR as it's included in another one

2024-01-18 00:52 UTC, closed without merging

2024-01-23 20:02 UTC, Titus-von-Koeller commented
> I think a question is if we should select the highest or lowest compute capability. The lowest would give the most broad support for multiple GPU. However, it is common that one uses an old GPU for monitors and a new GPU for deep learning work. As such, one would want to select the highest compute capability

I agree, highest is a good choice. We'll see if this is contrary to people's needs or expectations. If that is the case, we can add some logic to make it configurable.

Thanks a lot @Ronnoc for your contribution!